const qNotes = [
    'Terminal',
    'versioncontrol',
    'introjava',
    'primitive-data-types',
    'reference-data-types',
    'string-handling',
    'variable-declaration----',
    'arrays',
    'booleans',
    'logical-and-comparison-op-',
    '.equals()-and-comments',
    'errors',
    'strictly-typed',
    'instantianting-a-class',
    'primitive-and-nonprimitive',
    'operators',
    'attributes-and-Instance-variables',
    'classes-and-Reference-data-types',
    'creating-objects',
    'constructors',
    'strings',
    'dot-notation',
    'encapsulation',
    'access-modifiers',
    'interface',
    'getters',
    'setters',
    'this-keyword',
    'wrapper-classes',
    'strings2'
];

export default qNotes;